### ISSUE TITLE
Planning Checkpoint Review

### ISSUE THREAD

**Issue by murphyslemon** [murphyslemon/RecoveryAndStressMeter#12]
## Planning Checkpoint Review

- [x] Add image descriptions in project description of readme
- [x] add more info about schedule and pic in readme
- [x] Assess if risk assessment is needed
- [x] Time log document, how to add to github and what to do on it
- [x] Update GANTT 
- [x] Proof read all documents
- [x] update any new docs on Teams
- [x] update GitLab to match current version on GitHub/ sync GitLab and GitHub
- [x] add keijo to gitlab and teams
- [x] submit everything for review by project leader

**Comment by princesswarr** [comment]
This was done last period :)
